apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: 
    app: ngdep
  annotations:
    "kubernetes.io/change-cause": "Updated to alpine version"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.27.1-alpine
        ports:
        - containerPort: 80