apiVersion: v1
kind: Pod
metadata:
  name: trafficgen
  labels:
    name: trafficgen
spec:
  containers:
  - name: trafficgen-container
    image: docker123rakesh/trafficgenerator:v1
    args:
    #FQDN - <servicename>.<namespace>.svc.cluster.local
    - "colorapp-svc.dev.svc.cluster.local:80/api"
    - "5"
