apiVersion: v1
kind: Secret
metadata:
  name: mongo-colordb-credntial
  labels:
    app: mongodb
type: Opaque
data:
  password: Y29sb3JkYl9wYXNzd29yZA== #colordb_password
  username: Y29sb3JkYl91c2Vy #colordb_user
